djangopizza/products/urls.py
from django.urls import path
from .views import ProductList

app_name = "products"

urlpatterns = [
    path('', ProductList.as_view(), name="product-list")
]

djangopizza/urls.py
from django.contrib import admin
from django.urls import path, include
from djangopizza.products import urls as product_urls
from djangopizza.orders import urls as order_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include(order_urls, namespace='orders')),
    path('', include(product_urls, namespace='products'))
]

djangopizza/products/models.py
from django.db import models
from django.urls import reverse

CATEGORY_CHOICES = (
    ('P', 'pizza'),
    ('S', 'side'),
    ('D', 'drink'),
)

class Product(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField(max_length=500)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2, default="P")
    image_url = models.URLField(max_length=500, blank=True, null=True)

    def get_add_to_cart_absolute_url(self):
        return reverse("orders:add-to-cart", kwargs={
            'product_id': self.id
        })

    def get_remove_from_cart_absolute_url(self):
        return reverse("orders:remove-from-cart", kwargs={
            'product_id': self.id
        })

    def __str__(self):
        return self.title

djangopizza/products/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic import ListView, View
from .models import Product

class ProductList(View):

    def get(self, *args, **kwargs):
        object_list = Product.objects.all()
        category = self.request.GET.get('category', '')
        if category:
            object_list = object_list.filter(
                category=category
            )
        search_term = self.request.GET.get('search_term', '')
        if search_term:
            object_list = object_list.filter(
                title__icontains=search_term
            )
        paginator = Paginator(object_list, 8)

        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(self.request, 'products/list.html', {'page_obj': page_obj})

djangopizza/products/templates/products/list.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}Menu{% endblock %}

{% block content %}

<!--Main layout-->
    <main>
        <div class="container pt-5">

        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-5 mb-3">

            <!-- Navbar brand -->
            <span class="navbar-brand">Categories:</span>

            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if not request.GET.category %}active{% endif %}">
                <a class="nav-link" href="{% url 'products:product-list' %}">All</a>
                </li>
                <li class="nav-item {% if request.GET.category == 'P' %}active{% endif %}">
                <a class="nav-link" href="{% url 'products:product-list' %}?category=P">Pizzas</a>
                </li>
                <li class="nav-item {% if request.GET.category == 'S' %}active{% endif %}">
                <a class="nav-link" href="{% url 'products:product-list' %}?category=S">Sides</a>
                </li>
                <li class="nav-item {% if request.GET.category == 'D' %}active{% endif %}">
                <a class="nav-link" href="{% url 'products:product-list' %}?category=D">Drinks</a>
                </li>

            </ul>
            <!-- Links -->

            <form action="{% url 'products:product-list' %}" class="form-inline">
                <div class="md-form my-0">
                    <input type="submit" style="visibility: hidden;" />
                    {% if request.GET.category %}<input type="hidden" name="category" value="{{ request.GET.category }}" />{% endif %}
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" id="search_term" name="search_term">
                </div>                
            </form>
            </div>
            <!-- Collapsible content -->

        </nav>
        <!--/.Navbar-->

        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
        {% endif %}

        <!--Section: Products v.3-->
        <section class="text-center mt-5 mb-4">

            <!--Grid row-->
            <div class="row wow fadeIn">
            {% for product in page_obj %}
                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4">

                    <!--Card-->
                    <div class="card">

                    <!--Card image-->
                    <div class="view overlay">
                        {% if product.image_url %}
                            <img src="{{ product.image_url }}" class="card-img-top p-4" alt="{{ product.title }}">
                        {% else %}
                            {% with 'img/placeholders/'|add:product.get_category_display|add:'.svg' as image_static %}
                                <img src="{% static image_static %}" class="card-img-top p-4" alt="{{ product.title }}">
                            {% endwith %}                    
                        {% endif %}
                        <a>
                        <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                    <!--Card image-->

                    <!--Card content-->
                    <div class="card-body text-center">
                        <!--Category & Title-->
                        <a href="" class="grey-text">
                        <h5>{{ product.get_category_display|title }}</h5>
                        </a>
                        <h5>

                        {% if product.get_category_display == "pizza" %}
                        <i class="fa fa-xs fa-info-circle text-info" aria-hidden="true"
                            data-toggle="tooltip" data-placement="right" title="{{ product.description }}"></i>
                        {% endif %}

                        <strong>
                            <a href="" class="dark-grey-text">{{ product.title }}</a>
                        </strong>
                        </h5>

                        <h4 class="font-weight-bold blue-text">
                        <strong>${{ product.price }}</strong>
                        </h4>                        

                        <a href="{{ product.get_add_to_cart_absolute_url }}" class="btn btn-primary btn-md my-0 p">Add to cart
                            <i class="fas fa-shopping-cart ml-1"></i>
                        </a>

                    </div>
                    <!--Card content-->

                    </div>
                    <!--Card-->

                </div>
                <!--Grid column-->
                {% if forloop.last %}
                    </div>
                {% else %}
                    {% if forloop.counter|divisibleby:"4" %}
                    </div><div class="row wow fadeIn">
                    {% endif %}
                {% endif %}
            {% empty %}
                <div class="col-lg-12 col-md-12 mb-12 text-center">
                    No results found.
                </div>
            </div>
            {% endfor %}

        </section>
        <!--Section: Products v.3-->

        <!--Pagination-->
        {% comment %} {% if is_paginated %} {% endcomment %}
        <nav class="d-flex justify-content-center wow fadeIn">
            <ul class="pagination pg-blue">

            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}" aria-label="Previous">
                <span class="font-weight-bold" aria-hidden="true">&laquo;</span>
                <span class="sr-only">First</span>
                </a>
            </li>
            <!--Arrow left-->
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
                </a>
            </li>
            {% endif %}

            <li class="page-item active">
                <a class="page-link" href="?page={{ page_obj.number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
                </a>
            </li>

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}" aria-label="Next">
                <span class="font-weight-bold" aria-hidden="true">&raquo;</span>
                <span class="sr-only">Last</span>
                </a>
            </li>
            {% endif %}
            </ul>
        </nav>
        <!--Pagination-->
        {% comment %} {% endif %} {% endcomment %}

        </div>
    </main>
    <!--Main layout-->

{% endblock content %}