djangopizza/orders/urls.py
from django.urls import path
from .views import add_to_cart, remove_from_cart, OrderSummaryView, CheckoutView, OrderHistoryView

app_name = "orders"

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('order-summary/', OrderSummaryView.as_view(), name="summary"),
    path('order-history/', OrderHistoryView.as_view(), name="history"),
    path('add-to-cart/<product_id>', add_to_cart, name="add-to-cart"),
    path('remove-from-cart/<product_id>', remove_from_cart, name="remove-from-cart")
]

djangopizza/products/urls.py
from django.urls import path
from .views import ProductList

app_name = "products"

urlpatterns = [
    path('', ProductList.as_view(), name="product-list")
]

djangopizza/urls.py
from django.contrib import admin
from django.urls import path, include
from djangopizza.products import urls as product_urls
from djangopizza.orders import urls as order_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include(order_urls, namespace='orders')),
    path('', include(product_urls, namespace='products'))
]

djangopizza/orders/models.py
from django.db import models
from django.conf import settings
from djangopizza.products.models import Product
from django_countries.fields import CountryField

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(
        'Order',
        on_delete=models.CASCADE,
        related_name="items",
        blank=True,
        null=True,
    )
    quantity = models.IntegerField(default=1)

    def get_total_price(self):
        return self.quantity * self.product.price

    def __str__(self):
        return str(self.quantity) + " of " + self.product.title


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField(blank=True, null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    delivery = models.ForeignKey(
        'Delivery',
        on_delete=models.SET_NULL,
        default=1,
        blank=True,
        null=True,
    )
    shipping_address = models.ForeignKey(
        'ShippingAddress',
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )

    def get_total_price(self):
        total = 0
        for item in self.items.all():
            total += item.get_total_price()
        return total

    def get_total_price_with_delivery(self):
        return self.get_total_price() + self.delivery.cost

    def __str__(self):
        return self.user.username


class ShippingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100, blank=True, null=True)
    country = CountryField(multiple=False)
    zip_code = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username


class Delivery(models.Model):
    cost = models.FloatField()
    country = CountryField(multiple=False, blank=True, null=True, unique=True)

    def __str__(self):
        if not self.country:
            return "Generic Delivery"
        else:
            return f"Delivery to {self.country}"

djangopizza/products/models.py
from django.db import models
from django.urls import reverse

CATEGORY_CHOICES = (
    ('P', 'pizza'),
    ('S', 'side'),
    ('D', 'drink'),
)

class Product(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField(max_length=500)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2, default="P")
    image_url = models.URLField(max_length=500, blank=True, null=True)

    def get_add_to_cart_absolute_url(self):
        return reverse("orders:add-to-cart", kwargs={
            'product_id': self.id
        })

    def get_remove_from_cart_absolute_url(self):
        return reverse("orders:remove-from-cart", kwargs={
            'product_id': self.id
        })

    def __str__(self):
        return self.title

djangopizza/orders/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

class CheckoutForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'First Name',
        'id': 'first_name',
        'class': 'form-control',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Last Name',
        'id': 'last_name',
        'class': 'form-control',
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': 'youremail@example.com',
        'id': 'email',
        'class': 'form-control',
    }))
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '1234 Main St',
        'id': 'street_address',
        'class': 'form-control',
    }))
    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Apartment or Suite',
        'id': 'apartment_address',
        'class': 'form-control',
    }))
    country = CountryField(blank_label='(select country)').formfield(
        widget=CountrySelectWidget(attrs={
            'id': 'country',
            'class': 'custom-select d-block w-100',
        }
    ))
    zip_code = forms.CharField(widget=forms.TextInput(attrs={
        'id': 'zip_code',
        'class': 'form-control',
    }))

djangopizza/orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views.generic import View
from django.utils import timezone
from .models import Order, OrderItem, ShippingAddress
from .forms import CheckoutForm
from djangopizza.products.models import Product


class OrderHistoryView(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        orders = Order.objects.filter(
            user=self.request.user,
            is_ordered=True
        )
        context = {
            'orders': orders
        }
        return render(self.request, 'orders/history.html', context)

class CheckoutView(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        first_name = self.request.user.first_name
        last_name = self.request.user.last_name
        email = self.request.user.email

        shipping_address_qs = ShippingAddress.objects.filter(
            user=self.request.user,
        )

        if shipping_address_qs.exists():
            shipping_address = shipping_address_qs[0]
            form = CheckoutForm(initial={
                'first_name': first_name,
                'last_name': last_name,
                'email': email,
                'street_address': shipping_address.street_address,
                'apartment_address': shipping_address.apartment_address,
                'country': shipping_address.country,
                'zip_code': shipping_address.zip_code,
            })
        else:
            form = CheckoutForm(initial={
                'first_name': first_name,
                'last_name': last_name,
                'email': email,
            })
        try:
            order = Order.objects.get(
                user=self.request.user,
                is_ordered=False
            )
            if not order.items.exists() or order.get_total_price() == 0:
                messages.warning(self.request, "You do not have anything to checkout.")
                return redirect("products:product-list")
            context = {
                'form': form,
                'order': order
            }
            return render(self.request, 'orders/checkout.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order.")
            return redirect("products:product-list")        

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(
                user=self.request.user,
                is_ordered=False
            )
            if form.is_valid():
                user = self.request.user
                user.first_name = form.cleaned_data.get('first_name')
                user.last_name = form.cleaned_data.get('last_name')
                user.email = form.cleaned_data.get('email')
                user.save()

                shipping_address, created = ShippingAddress.objects.get_or_create(
                    user=user,
                    street_address = form.cleaned_data.get('street_address'),
                    apartment_address = form.cleaned_data.get('apartment_address'),
                    country = form.cleaned_data.get('country'),
                    zip_code = form.cleaned_data.get('zip_code'),
                )
                if created:
                    shipping_address.save()
                order.shipping_address = shipping_address
                order.ordered_date = timezone.now()
                order.is_ordered = True
                order.save()
                messages.success(self.request, "You have successfully placed an order!")
                return redirect("products:product-list")
            messages.warning(self.request, "Failed to process checkout form")
            return redirect("orders:checkout")
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order.")
            return redirect("products:product-list")
        

class OrderSummaryView(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(
                user=self.request.user,
                is_ordered=False
            )
            context = {
                'object': order
            }
            return render(self.request, 'orders/summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order.")
            return redirect("products:product-list")
        


@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)    
    order_qs = Order.objects.filter(
        user=request.user,
        is_ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(product__id=product_id).exists():
            order_item = order.items.get(product__id=product_id)
            order_item.quantity += 1
            order_item.save()
            messages.info(request, f"{product.title} quantity has been updated.")
        else:
            order.items.create(
                product=product,
                user=request.user
            )
            messages.info(request, f"{product.title} has been added to your cart.")
    else:
        order = Order.objects.create(user=request.user)
        order.items.create(
            product=product,
            user=request.user
        )
        messages.info(request, f"{product.title} has been added to your cart.")
    return redirect(request.META.get('HTTP_REFERER', "orders:summary"))


@login_required
def remove_from_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    order_qs = Order.objects.filter(
        user=request.user,
        is_ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(product__id=product_id).exists():
            order_item = order.items.get(product__id=product_id)
            if order_item.quantity == 1:
                order.items.remove(order_item)
                messages.info(request, f"{product.title} has been removed from your cart.")
            else:
                order_item.quantity -= 1
                order_item.save()
                messages.info(request, f"{product.title} quantity has been updated.")
        else:
            messages.info(request, f"{product.title} was not in your cart.")
    else:
        messages.info(request, "You do not have an active order.")
    return redirect(request.META.get('HTTP_REFERER', "orders:summary"))

djangopizza/products/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic import ListView, View
from .models import Product

class ProductList(View):

    def get(self, *args, **kwargs):
        object_list = Product.objects.all()
        category = self.request.GET.get('category', '')
        if category:
            object_list = object_list.filter(
                category=category
            )
        search_term = self.request.GET.get('search_term', '')
        if search_term:
            object_list = object_list.filter(
                title__icontains=search_term
            )
        paginator = Paginator(object_list, 8)

        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(self.request, 'products/list.html', {'page_obj': page_obj})

djangopizza/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Django Pizza - {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
        height: 60vh;
        }

        @media (max-width: 740px) {

        html,
        body,
        header,
        .carousel {
            height: 100vh;
        }
        }

        @media (min-width: 800px) and (max-width: 850px) {

        html,
        body,
        header,
        .carousel {
            height: 100vh;
        }
        }

    </style>
</head>

<body>

    {% include "navbar.html" %}
  
    {% block content  %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}    
</body>

</html>

djangopizza/templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
    <a href="https://stackoverflow.com/users/5633261/evgenii-klepilin" target="_blank">
        <i class="fab fa-stack-overflow mr-3"></i>
    </a>

    <a href="https://www.linkedin.com/in/evgeniiklepilin/" target="_blank">
        <i class="fab fa-linkedin mr-3"></i>
    </a>

    <a href="https://github.com/EvgeniiKlepilin/" target="_blank">
        <i class="fab fa-github mr-3"></i>
    </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
    © 2020 Copyright: <a href="https://www.linkedin.com/in/evgeniiklepilin/" target="_blank">Evgenii Klepilin</a>. Made with 
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

</footer>
<!--/.Footer-->

djangopizza/templates/navbar.html
{% load cart_template_tags %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'products:product-list' %}">
        <strong class="red-text">Django Pizza <i class='fas fa-pizza-slice'></i></strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'orders:history' %}">Order History</a>
            </li>
            {% endif %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'orders:summary' %}">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a href="https://github.com/EvgeniiKlepilin/django-pizza" class="nav-link border border-light rounded waves-effect"
            target="_blank">
            <i class="fab fa-github mr-2"></i>Django Pizza GitHub
            </a>
        </li>
        </ul>

    </div>

    </div>
</nav>
<!-- Navbar -->

djangopizza/templates/scripts.html
{% load static %}

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();
    // Tooltips Initialization
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })

</script>